# RHEL 7/8 CIS section 1 fixes
---
- name: 'Install some RHEL packages for container tests'
  yum:
    name: "{{ lookup('vars', 'pkgs_to_install') }}"
    enablerepo: "{{ lookup('vars', 'enablerepo_'+ ansible_os_family  + ansible_distribution_major_version) }}"
    state: present
    releasever: "{{ ansible_distribution_version }}"
  when:
    - ansible_virtualization_type == 'docker'
  tags:
    - level3
    - rhel7
    - csops

# We want different behavior from the default role for servers with/without CIS hardening
- name: 'Ensure facts directory exists'
  file:
    dest: "{{ cis_ansible_facts_dir }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags:
    - cis_fact
    - level1
    - level2
    - level3
    - rhel7
    - rhel8
    - csops

- name: 'Drop a CIS Ansible fact for the SSH and su rules in the default role'
  template:
    src: 'cis.fact.j2'
    dest: "{{ cis_ansible_facts_dir }}/cis.fact"
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags:
    - cis_fact
    - level1
    - level2
    - level3
    - rhel7
    - rhel8
    - csops

# - name: '1.1.5: Ensure noexec option set on /tmp partition' - won't do

- name: '1.1.17: Add noexec option to /dev/shm partition'
  mount: >
      name='/dev/shm'
      src='none'
      state=mounted
      fstype='tmpfs'
      opts='nodev,nosuid,noexec'
  tags:
    - 1_1_17
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

# - name: '1.1.22: Disable automounting' - level 3 task

- name: '1.2.2: Ensure gpgcheck is globally activated'
  replace:
    name: /etc/yum.repos.d/redhat.repo
    regexp: '^gpgcheck=0'
    replace: 'gpgcheck=1'
  tags:
    - 1_2_2
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

- name: '1.3.1: Install aide if needed'
  package:
    name: aide
    state: present
  tags:
    - 1_3_1
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

- name: '1.3.2: Ensure filesystem integrity is regularly checked'
  cron:
    name: 'aide'
    job: '/usr/sbin/aide --check'
    cron_file: '/etc/crontab'
    user: 'root'
    month: '*'
    day: '*'
    hour: '02'
    minute: '00'
    state: present
  tags:
    - 1_3_2
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

- name: 'Test for bootloader config'
  stat:
    path: "{{ cis_bootloader_cfg }}"
  register: grub_cfg_file
  tags:
    - 1_4_1
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

- name: '1.4.1: Ensure permissions on bootloader config are configured'
  file:
    path: "{{ cis_bootloader_cfg }}"
    owner: 'root'
    group: 'root'
    mode: '0400'
  when:
    - grub_cfg_file.stat.exists
  tags:
    - 1_4_1
    - section1
    - level1
    - rhel7
    - rhel8
    - csops

# - name: '1.4.2: Ensure bootloader password is set' - won't do
